### ISSUE TITLE
Add `as_typst()` function to support styled tables in `typst` Quarto output format

### ISSUE THREAD

**Issue by elipousson** [rstudio/gt#1500]
## Prework

- [X] Read and abide by **gt**'s [code of conduct](https://www.contributor-covenant.org/version/2/1/code_of_conduct.html) and [contributing guidelines](https://github.com/rstudio/gt/blob/master/.github/CONTRIBUTING.md).
- [X] Search for duplicates among the [existing issues](https://github.com/rstudio/gt/issues) (both open and closed).

## Proposal

This may be premature given that the `typst` format is pre-release but I figured I'd offer the suggestion now that a `as_typst()` function that supports or enables custom table formatting when using the `typst` Quarto output format could be a great addition.

Some background via [the Quarto documentation](https://quarto.org/docs/prerelease/1.4/typst.html):

>Quarto v1.4 includes support for the typst output format. [Typst](https://github.com/typst/typst) is a new open-source markup-based typesetting system that is designed to be as powerful as LaTeX while being much easier to learn and use.

The Quarto repo already has a related issue for incorporating the [typst-tablex](https://github.com/PgBiel/typst-tablex) library for table formatting: https://github.com/quarto-dev/quarto-cli/issues/6811 Not sure if that would make a `as_typst()` function unnecessary or if the two could work in concert.

**Comment by andrie** [comment]
It seems to me that this `typst` package is going to be relevant for this work: https://github.com/typst/packages/tree/main/packages/preview/tablex/0.0.8

**Comment by sda030** [comment]
Updates to Typst's included table formatting on the way: https://staging.typst.app/docs/changelog

**Comment by olivroy** [comment]
I think this is resolved natively with Quarto 1.5 https://quarto.org/docs/blog/posts/2024-07-02-beautiful-tables-in-typst/

**Comment by roaldarbol** [comment]
I'd just add that for some workflows, the native Quarto solution doesn't solve the issue - I usually save my tables to also incorporate them into other LaTeX documents (`mytable |> gtsave("mytable.tex"`). It would definitely be great to be able to export a Typst table. Hopefully the native conversion may aid that, but I don't think the issue is resolved yet.

**Comment by sverrirarnors** [comment]
@olivroy, it's at least not fully resolved I think. Quarto's CSS conversions do not look good in typst pdf documents and I have had a lot of issues trying to make gt tables look good.

> I think this is resolved natively with Quarto 1.5 (just released last week) https://quarto.org/docs/blog/posts/2024-07-02-beautiful-tables-in-typst/
